// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu0DSdkdL9u57r1BB-pdIiqBrSv8RwPbo',
    appId: '1:288293599753:web:de99d0d6856c8ef77256d8',
    messagingSenderId: '288293599753',
    projectId: 'kargolast-125f6',
    authDomain: 'kargolast-125f6.firebaseapp.com',
    storageBucket: 'kargolast-125f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKoFZyDfeidFcPzRoGNFGURNGTJ2b9BE4',
    appId: '1:288293599753:android:b74587d456351d817256d8',
    messagingSenderId: '288293599753',
    projectId: 'kargolast-125f6',
    storageBucket: 'kargolast-125f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpL3XwJpzRY_kE1CqeP7bl3K7nYUBzh74',
    appId: '1:288293599753:ios:882cb61e4d8279ae7256d8',
    messagingSenderId: '288293599753',
    projectId: 'kargolast-125f6',
    storageBucket: 'kargolast-125f6.appspot.com',
    iosBundleId: 'com.example.kargo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpL3XwJpzRY_kE1CqeP7bl3K7nYUBzh74',
    appId: '1:288293599753:ios:882cb61e4d8279ae7256d8',
    messagingSenderId: '288293599753',
    projectId: 'kargolast-125f6',
    storageBucket: 'kargolast-125f6.appspot.com',
    iosBundleId: 'com.example.kargo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu0DSdkdL9u57r1BB-pdIiqBrSv8RwPbo',
    appId: '1:288293599753:web:a9320b01c5bc980d7256d8',
    messagingSenderId: '288293599753',
    projectId: 'kargolast-125f6',
    authDomain: 'kargolast-125f6.firebaseapp.com',
    storageBucket: 'kargolast-125f6.appspot.com',
  );
}
